### ISSUE TITLE
Makefile

### ISSUE THREAD

**Issue by yramachers** [SuperNEMO-DBD/SuperNEMOValidationTool#15]
Hi Cheryl,
your Makefile is a little on the private use side. I've made a cmake script for more general install:

cmake_minimum_required(VERSION 3.3)
project(ValidationParser)
set (CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++11")

find_package(ROOT REQUIRED)
find_package(Boost REQUIRED filesystem system)

include_directories(${ROOT_INCLUDE_DIRS} ${Boost_INCLUDE_DIRS} include)

add_executable(ValidationParser ValidationParser.cxx ValidationParser.h)
target_link_libraries(ValidationParser ${ROOT_LIBRARIES} ${Boost_LIBRARIES})

Sorry for the basic copy/paste but it is really very short, so couldn't resist the paste. Just call it CMakeLists.txt and all should be fine in a Cadfael environment (that's where cmake actually finds Boost and Root simply with the find command). The in the build directory, say cmake .. and it compiles for me (well, see below).

Next, your code does not compile for me. Please find/replace all 'isnan()' and 'isinf()' functions with 'std::isnan()' and 'std::isinf()', otherwise they are flagged as ambiguous by the compiler. It is anyway always a good idea to avoid 'using namespace std' wherever you can for that very reason. Here you can leave it as is and insert the 'std::' anyway. Will work and no harm done.

**Comment by cherylepatrick** [comment]
Thanks Yorck, I am so bad at makefiles/CMake. Strange that I don't get those errors - maybe I have a less fussy compiler version or something? Anyway I will add the std:: if that fixes it. Thanks lots for testing, I really appreciate it.

**Comment by yramachers** [comment]
We have recently changed to CentOS7 here at Warwick and use gcc5.5 for Falaise. Could be that.

**Comment by cherylepatrick** [comment]
Oh could be. To be honest I have only run it on the mac. I am really glad someone else is trying this before I announce it to everyone at the meeting, it will be great if it is working as a proper user tool out of the box.
