### ISSUE TITLE
command line option help

### ISSUE THREAD

**Issue by yramachers** [SuperNEMO-DBD/SuperNEMOValidationTool#17]
Maybe a little too pedantic but all command line executables I have ever come across had a --help or -h option. Your usage option print comes up which is nice but -h is unknown. I know, pedantic...

**Comment by cherylepatrick** [comment]
Eh, but it is easy to fix. No problem to add it. This is just the sort of thing that you don't see when you look at your own stuff (obviously I know how it works and don't need to ask for the help very often...)

**Comment by cherylepatrick** [comment]
Should be fixed by #18
